name = "htmlshare"
compatibility_date = "2024-11-28"

[[kv_namespaces]]
binding = "SESSION"
preview_id = "TBD"
id = "TBD"

[env.production]
name = "htmlshare"

[[env.production.d1_databases]]
binding = "DB"
database_name = "htmlshare-db"
database_id = "TBD"

[[env.production.kv_namespaces]]
binding = "SESSION"
preview_id = "TBD"
id = "TBD"

[build]
command = "npm run build"
