name = "htmlshare-astro"
compatibility_date = "2024-01-01"

# Local development database
[[d1_databases]]
binding = "DB"
database_name = "htmlshare-db"
database_id = "88b9d37a-02d2-45a3-9d83-3c641f708bb7"

[env.production.vars]
ENVIRONMENT = "production"

# Production database
[[env.production.d1_databases]]
binding = "DB"
database_name = "htmlshare-db"
database_id = "88b9d37a-02d2-45a3-9d83-3c641f708bb7"