name = "htmlshare"
compatibility_date = "2024-11-28"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "htmlshare-db"
database_id = "88b9d37a-02d2-45a3-9d83-3c641f708bb7"

[[kv_namespaces]]
binding = "SESSION"
preview_id = "TBD"
id = "TBD"

[env.production]
name = "htmlshare"

[[env.production.d1_databases]]
binding = "DB"
database_name = "htmlshare-db"
database_id = "88b9d37a-02d2-45a3-9d83-3c641f708bb7"

[[env.production.kv_namespaces]]
binding = "SESSION"
preview_id = "TBD"
id = "TBD"
